export { default as Blockquote } from './quote/Blockquote.vue';
export { default as ScrollyvueUiKicker } from './kicker/Kicker.vue';
export { default as ScrollyvueUiTeaser } from './teaser/Teaser.vue';
export { default as ScrollyvueUiChart } from './chart/Chart.vue';
export { default as ScrollyvueUiImage } from './image/Image.vue';
export { default as ScrollyvueUiQuote } from './quote/Quote.vue';
export { default as ScrollyvueUiText } from './text/Text.vue';
export { default as ScrollyvueUiTitle } from './title/Title.vue';
export { default as ScrollyvueUiSpinner } from './spinner/Spinner.vue';
export { default as ScrollyvueUiCard } from './card/Card.vue';
export { default as ScrollyvueUiButton } from './button/Button.vue';
export { default as ScrollyvueUiSparkline } from './sparkline/Sparkline.vue';
export { vuetify } from './vuetify/vuetify';
